name: CI
on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sivchari/actions-kit@main
        with:
          skip-goreleaser-check: true

